name: Docker (CUDA Suport)

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - "docker-compose.yml"
      - "docker-compose.dev.yml"
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
      - ".github/release-drafter.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "Dockerfile-gpu.dev"
      - "scripts/dev-gpu.sh"
      - "scripts/dev.sh"
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/tiimk/serge
          flavor: |
            suffix=-cuda,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOK }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-gpu.dev
          push: ${{ github.event_name != 'pull_request' }}
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
